
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-server-crd
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-bigip-ctlr
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: k8s-bigip-ctlr
      containers:
        - name: cntr-ingress-svcs
          image: registry.connect.redhat.com/f5networks/cntr-ingress-svcs:latest
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Replace with the name of the Secret containing your login
                  # credentials
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
              "--bigip-username=$(BIGIP_USERNAME)",
              "--bigip-password=$(BIGIP_PASSWORD)",
              "--bigip-url=192.168.200.3",
              "--bigip-partition=crd",
              "--namespace=default",
              "--pool-member-type=cluster",
              "--openshift-sdn-name=/Common/openshift-vxlan",
              "--log-level=DEBUG",
              "--insecure=true",
              "--custom-resource-mode=true",
              "--as3-validation=true",
              "--log-as3-response=true",
              "--disable-teems=true",
            ]
      imagePullSecrets:
        - name: f5-docker-images
        - name: bigip-login