apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  name: f5-server
  namespace: kube-system
spec:
  args:
    log_as3_response: true
    manage_routes: true
    agent: as3
    log_level: DEBUG
    route_vserver_addr: 10.0.15.95
    bigip_partition: ocp
    openshift_sdn_name: /Common/openshift-vxlan
    bigip_url: https://10.0.15.95:8443
    insecure: true
    pool-member-type: cluster
  bigip_login_secret: bigip-login
  image:
    pullPolicy: Always
    repo: k8s-bigip-ctlr
    user: f5networks
  namespace: kube-system
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
    name: null
  version: latest
