#!/bin/bash
# https://clouddocs.f5.com/training/community/containers/html/class2/module1/lab1.html
tmsh create auth partition okd

#create kubernetes bigip container connecter w/ nodeport, authentication and RBAC
oc create secret generic bigip-login -n kube-system --from-literal=username=admin --from-literal=password=bigip123
#oc create serviceaccount bigip-ctlr -n kube-system
#oc create -f f5-kctlr-openshift-clusterrole.yaml
oc create serviceaccount k8s-bigip-ctlr -n kube-system
oc create clusterrolebinding k8s-bigip-ctlr-clusteradmin --clusterrole=cluster-admin --serviceaccount=kube-system:k8s-bigip-ctlr
oc create -f f5-nodeport-deployment.yaml
oc create -f myf5-hello-world-deployment.yaml
#NodePort
oc create -f myf5-hello-world-service.yaml
## create route

## for AWS, need to add rules to allow high port

