apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  name: f5-server
  namespace: kube-system
spec:
  args:
    log_as3_response: true
    manage_routes: true
    agent: as3
    log_level: DEBUG
    route_vserver_addr: 10.0.26.89
    bigip_partition: openshift
    bigip_url: https://10.0.26.89:8443
    insecure: true
    pool-member-type: nodeport
  bigip_login_secret: bigip-login
  image:
    pullPolicy: Always
    repo: k8s-bigip-ctlr
    user: f5networks
  namespace: kube-system
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
    name: null
  version: latest
